# Default values for eck-kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

version: 7.8.1

# Max size of CSV reports
xpackReportingCSVMaxsizebytes: "1048576000"

ingress:
  enabled: true
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: kibana.blacklab.lan
      paths:
      - path: /*
        backend:
          serviceName: kibana-kb-http
          servicePort: 5601
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi

nodeSelector: {}
# nodeSelector:
#   dedicated: dataeng

tolerations: []
# tolerations:
# - key: dedicated
#   operator: Equal
#   value: dataeng
#   effect: NoSchedule

affinity: {}