apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-logger.fullname" . }}
  labels:
    {{- include "cloud-logger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: healthz
      port: {{ .Values.service.healthzPort }}
      targetPort: {{ .Values.service.healthzPort }}
      protocol: TCP
  selector:
    {{- include "cloud-logger.selectorLabels" . | nindent 4 }}
